// Generated by CoffeeScript 1.6.3
(function($) {
  var Item, List, ListView, listView;
  Item = Backbone.Model.extend({
    defaults: {
      part1: "hello",
      part2: "world"
    }
  });
  List = Backbone.Collection.extend({
    model: Item
  });
  ListView = Backbone.View.extend({
    el: $("body"),
    events: {
      "click button#add": "addItem"
    },
    initialize: function() {
      _.bindAll(this, "render", "addItem", "appendItem");
      this.collection = new List;
      this.collection.bind("add", this.appendItem);
      this.counter = 0;
      return this.render();
    },
    render: function() {
      var item, _i, _len, _ref, _results;
      $(this.el).append("<button id='add'>+</button>");
      $(this.el).append("<ul></ul>");
      _ref = this.collection.models;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        _results.push(this.appendItem(item));
      }
      return _results;
    },
    addItem: function() {
      this.counter++;
      return $("ul", this.el).append("<li>Hello, " + this.counter + "</li>");
    }
  });
  return listView = new ListView;
})(jQuery);
